POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vb3QiLCJpZCI6IjYxODNkOTI2OGRlMzVmNGMwOGE2MDk4NyIsImlhdCI6MTYzNjAzMjEwNiwiZXhwIjoxNjM2MDM1NzA2fQ.qY-8AmkLyoslAojayJpgj--IJ0GKFRkJCUzgblp-COc

{
  "title": "@eee",
  "author": "moot",
  "url": "https://goosssgleedsed.com",
  "likes": "332"
}